# Add CI specific values ########################################
### CONFIG | Configuration Store Configs
### See aiSSEMBLE aissemble-configuration-store-chart: README for more details.
### https://github.com/boozallen/aissemble/
#########################################

aissemble-configuration-store-chart:
  aissemble-quarkus-chart:
    deployment:
      image:
        imagePullPolicy: IfNotPresent

  configurationVolume:
    storageType: "local"
    volumePathOnNode: "/Users/csun/bah/tests/test-313/src/main/resources/configurations"